tls:
  certificates:
    - certFile: "/etc/traefik/certs/${domain}.fullchain"
      keyFile: "/etc/traefik/certs/${domain}.key"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/${domain}.fullchain"
        keyFile: "/etc/traefik/certs/${domain}.key"

http:
  routers:
    nomad:
      service: nomad
      rule: Host(`nomad.${domain}`)
      entrypoints:
        - websecure
      middlewares:
        - auth

    consul:
      service: consul
      rule: Host(`consul.${domain}`)
      entrypoints:
        - websecure
      middlewares:
        - auth

    pfsense:
      service: pfsense
      rule: Host(`pfsense.${domain}`)
      entrypoints:
        - websecure
      middlewares:
        - auth

    pve:
      service: pve
      rule: Host(`pve.${domain}`)
      entrypoints:
        - websecure
      middlewares:
        - auth

    pve-backup:
      service: pve-backup
      rule: Host(`pve-backup.${domain}`)
      entrypoints:
        - websecure
      middlewares:
        - auth

  middlewares:
    auth:
      forwardAuth:
        address: http://auth.${consul_domain}:4181
        authResponseHeaders:
          - X-Forwarded-User
        trustForwardHeader: true

  services:
    nomad:
      loadbalancer:
        servers:
          - url: ${nomad_url} 

    consul:
      loadbalancer:
        servers:
          - url: ${consul_url}

    pfsense:
      loadbalancer:
        servers:
          - url: ${pfsense_url}
    
    pve:
      loadbalancer:
        servers:
          - url: ${pve_url}

    pve-backup:
      loadbalancer:
        servers:
          - url: ${pve_backup_url}
                    
