entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
#    proxyProtocol:
#      trustedIPs:
#        - 192.168.2.1
        
  websecure:
    address: :443
    http:
      tls: true
#    proxyProtocol:
#      trustedIPs:
#        - 192.168.2.1   

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
    
  consulCatalog:
    exposedByDefault: false
    defaultRule: Host(`{{ normalize .Name }}.${domain}`)
    endpoint:
      address: 127.0.0.1:8500

global:
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

api:
  insecure: false
  dashboard: true
  debug: false
  disabledashboardad: true

log:
  level: info
  # filePath: "/etc/traefik/logs"
  

accessLog:
  format: json
  filters:
    statusCodes:
      - 200
      - 300-302
      - 400-404