- platform: group
  name: Color lights
  unique_id: color_lights
  entities:
    - light.led_light
    - light.rocket_lamp
    - light.movie_lamp
    - light.loft_lamp

- platform: group
  name: Evening lights
  unique_id: evening_lights
  entities:
    - light.master_lamp_1
    - light.master_lamp_2
    - light.nook_light
    - light.sink_light
    
- platform: group
  name: Interior lights
  unique_id: interior_lights
  entities:
    - light.led_light
    - light.rocket_lamp
    - light.movie_lamp
    - light.loft_lamp
    - light.master_lamp_1
    - light.master_lamp_2
    - light.nook_light
    - light.sink_light
    - light.dining_light
    - light.entry_light
    - light.family_room_fan_light
    - light.family_room_lamp
    - light.guest_bath_vanity
    - light.master_bath_vanity
    - light.nook_bath_vanity
    - light.hall_lights
    - light.kitchen_lights
    - light.living_room_fan_light
    - light.living_room_lamp
    - light.loft_lights
    - light.mantle_lights
    - light.spare_room_light
    - light.master_bedroom_fan_light
    - light.guest_lamp_1
    - light.guest_lamp_2
    - light.water_closet_light
    - light.stairway_lights
  
